=== JonathanOReyesA/SIMA/common/persistence/src/main/resources/xml/callSP.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns="http://www.w3.org/2001/XMLSchema">
  <element name="callSP">
    <complexType>
      <sequence>
        <element type="string" name="storedProcedureName"/>
        <element type="boolean" name="function" minOccurs="0"/>
        <element type="boolean" name="cursor" minOccurs="0"/>
        <element name="parameter" maxOccurs="unbounded" minOccurs="0">
          <complexType>
            <sequence>
              <element type="string" name="parameterName"/>
              <element type="string" name="outParameter" minOccurs="0"/>
              <element type="string" name="typeParameter"/>
            </sequence>
          </complexType>
        </element>
        <element name="result" maxOccurs="unbounded" minOccurs="0">
          <complexType>
            <sequence>
              <element type="string" name="errorCodeParameterName"/>
              <element type="string" name="errorDescriptionParameterName" minOccurs="0"/>
              <element type="integer" name="successExecuteSPCode"/>
              <element type="string" name="successExecuteSPDescription" minOccurs="0"/>
              <element type="integer" name="errorExecuteSPCode" minOccurs="0"/>
              <element type="string" name="errorExecuteSPDescription" minOccurs="0"/>
            </sequence>
          </complexType>
        </element>
      </sequence>
    </complexType>
  </element>
</schema>

=== JonathanOReyesA/SIMA/common/persistence/src/main/resources/xml/callSP-SPSEARCHCLAIMPE.xml
<?xml version="1.0" encoding="UTF-8"?>
<callSP xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="callSP.xsd">
  <storedProcedureName>SPSEARCHCLAIM_PE</storedProcedureName>
  <function>true</function>
  <cursor>true</cursor>
  <parameter>
  	<parameterName>P_PARTNERID</parameterName>
  	<typeParameter>NUMERIC</typeParameter>
  </parameter>
  
    <parameter>
  	<parameterName>P_BUSINESSPARTNERID</parameterName>
  	<typeParameter>VARCHAR</typeParameter>
  </parameter>
  
    <parameter>
  	<parameterName>P_CLAIMID</parameterName>
  	<typeParameter>VARCHAR</typeParameter>
  </parameter>
  
  <parameter>
  	<parameterName>P_CERTIFICATE</parameterName>
  	<typeParameter>VARCHAR</typeParameter>
  </parameter>
  
</callSP>

=== JonathanOReyesA/SIMA/common/persistence/target/classes/xml/callSP-SPCREATEUPDATEMEDICO.xml
<?xml version="1.0" encoding="UTF-8"?>
<callSP xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="callSP.xsd">
	<storedProcedureName>SPCREATEUPDATEMEDICO</storedProcedureName>

	<parameter>
		<parameterName>P_ID_MEDICO</parameterName>
		<typeParameter>NUMERIC</typeParameter>
	</parameter>

	<parameter>
		<parameterName>P_CEDULA</parameterName>
		<typeParameter>VARCHAR</typeParameter>
	</parameter>

	<parameter>
		<parameterName>P_GIVENNAME</parameterName>
		<typeParameter>VARCHAR</typeParameter>
	</parameter>

	<parameter>
		<parameterName>P_MIDDLENAME</parameterName>
		<typeParameter>VARCHAR</typeParameter>
	</parameter>

	<parameter>
		<parameterName>P_FAMILYNAME</parameterName>
		<typeParameter>VARCHAR</typeParameter>
	</parameter>

	<parameter>
		<parameterName>P_ADDITIONALFAMILYNAME</parameterName>
		<typeParameter>VARCHAR</typeParameter>
	</parameter>

	<parameter>
		<parameterName>P_ESPECIALIDAD</parameterName>
		<typeParameter>VARCHAR</typeParameter>
	</parameter>

	<parameter>
		<parameterName>P_STATUS</parameterName>
		<typeParameter>VARCHAR</typeParameter>
	</parameter>
	
	<parameter>
		<parameterName>P_USER</parameterName>
		<typeParameter>VARCHAR</typeParameter>
	</parameter>

	<parameter>
		<parameterName>P_PARTNERID</parameterName>
		<typeParameter>NUMERIC</typeParameter>
	</parameter>

	<parameter>
		<parameterName>P_ERROR</parameterName>
		<outParameter>true</outParameter>
		<typeParameter>NUMERIC</typeParameter>
	</parameter>

	<parameter>
		<parameterName>P_ERROR_DESC</parameterName>
		<outParameter>true</outParameter>
		<typeParameter>VARCHAR</typeParameter>
	</parameter>
</callSP>

=== JonathanOReyesA/SIMA/common/persistence/target/classes/xml/callSP-SPCONFIRMATIONCLAIM.xml
<?xml version="1.0" encoding="UTF-8"?>
<callSP xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="callSP.xsd">
  <storedProcedureName>SPCONFIRMATIONCLAIM</storedProcedureName>

  <parameter>
  	<parameterName>P_CLAIMID</parameterName>
  	<typeParameter>VARCHAR</typeParameter>
  </parameter>
  
  <parameter>
  	<parameterName>P_ERROR</parameterName>
  	<outParameter>true</outParameter>
  	<typeParameter>NUMERIC</typeParameter>
  </parameter>
  
   <parameter>
  	<parameterName>P_ERR_DESC</parameterName>
  	<outParameter>true</outParameter>
  	<typeParameter>VARCHAR</typeParameter>
  </parameter>
  
  <result>
		<errorCodeParameterName>P_ERROR</errorCodeParameterName>
		<errorDescriptionParameterName>P_ERROR_DESC</errorDescriptionParameterName>
		<successExecuteSPCode>0</successExecuteSPCode>
	</result>

</callSP>

=== JonathanOReyesA/SIMA/common/persistence/target/classes/xml/callSP-SPUPDATESTATUSCLAIM.xml
<?xml version="1.0" encoding="UTF-8"?>
<callSP xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="callSP.xsd">
  <storedProcedureName>SPUPDATESTATUSCLAIM</storedProcedureName> 

	<parameter>
  		<parameterName>P_CLAIMID</parameterName>
  		<typeParameter>VARCHAR</typeParameter>
  	</parameter>
  	
	<parameter>
  		<parameterName>P_CLAIMSTATUSID</parameterName>
  		<typeParameter>NUMERIC</typeParameter>
  	</parameter>
  	
  	<parameter>
  		<parameterName>P_CLAIMSTATUSDATE</parameterName>
  		<typeParameter>DATE</typeParameter>
  	</parameter>
  	
  	<parameter>
  		<parameterName>P_CLAIMSTATUSUSER</parameterName>
  		<typeParameter>VARCHAR</typeParameter>
  	</parameter>
  	
  	<parameter>
  		<parameterName>P_PAYMENTTYPE</parameterName>
  		<typeParameter>VARCHAR</typeParameter>
  	</parameter>
  	
  	<parameter>
  		<parameterName>P_ERROR</parameterName>
  		<outParameter>true</outParameter>
  		<typeParameter>NUMERIC</typeParameter>
  	</parameter>
    <parameter>
  		<parameterName>P_ERROR_DESC</parameterName>
  		<outParameter>true</outParameter>
  		<typeParameter>VARCHAR</typeParameter>
  	</parameter>
</callSP>

=== JonathanOReyesA/SIMA/common/persistence/target/classes/xml/callSP-FNGETCLIENTES.xml
<?xml version="1.0" encoding="UTF-8"?>
<callSP xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="callSP.xsd">
	<storedProcedureName>FNGETCLIENTES</storedProcedureName>
	
	<function>true</function>
	<cursor>true</cursor>
	
	<parameter>
		<parameterName>P_BUSINESSPARTNERID</parameterName>
		<typeParameter>VARCHAR</typeParameter>
	</parameter>
	<parameter>
		<parameterName>P_BUSINESSPARTNERNAME</parameterName>
		<typeParameter>VARCHAR</typeParameter>
	</parameter>
	<parameter>
		<parameterName>P_BIRTHDATE</parameterName>
		<typeParameter>DATE</typeParameter>
	</parameter>
	<parameter>
		<parameterName>P_PARTNERID</parameterName>
		<typeParameter>NUMERIC</typeParameter>
	</parameter>

</callSP>

=== JonathanOReyesA/SIMA/common/persistence/src/main/resources/xml/callSP-SPCLAIMREJECTION.xml
<?xml version="1.0" encoding="UTF-8"?>
<callSP xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="callSP.xsd">
  <storedProcedureName>SPCLAIMREJECTION</storedProcedureName>

  <parameter>
  	<parameterName>P_CLAIMID</parameterName>
  	<typeParameter>VARCHAR</typeParameter>
  </parameter>
  
   <parameter>
  	<parameterName>P_CLAIMREJECTIONTYPEID</parameterName>
  	<typeParameter>NUMERIC</typeParameter>
  </parameter>
  
    <parameter>
  	<parameterName>P_REJECTIONAMOUNT</parameterName>
  	<typeParameter>NUMERIC</typeParameter>
  </parameter>
  
   <parameter>
  	<parameterName>P_REJECTIONDATE</parameterName>
  	<typeParameter>DATE</typeParameter>
  </parameter>
  
    <parameter>
  	<parameterName>p_REJECTIONDOCUMENTNAME</parameterName>
  	<typeParameter>VARCHAR</typeParameter>
  </parameter>
  
  <parameter>
  	<parameterName>P_ERROR</parameterName>
  	<outParameter>true</outParameter>
  	<typeParameter>NUMERIC</typeParameter>
  </parameter>
  
   <parameter>
  	<parameterName>P_ERRORDESC</parameterName>
  	<outParameter>true</outParameter>
  	<typeParameter>VARCHAR</typeParameter>
  </parameter>
  
</callSP>

=== JonathanOReyesA/SIMA/common/persistence/src/main/resources/xml/callSP-SPUPDATEIMPARAMETERS.xml
<?xml version="1.0" encoding="UTF-8"?>
<callSP xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="callSP.xsd">
  <storedProcedureName>SPUPDATEIMPARAMETERS</storedProcedureName>
  
  <parameter>
		<parameterName>P_PARAM_ID</parameterName>
		<typeParameter>NUMERIC</typeParameter>
	</parameter>

	<parameter>
		<parameterName>P_MAX_DIAS</parameterName>
		<typeParameter>NUMERIC</typeParameter>
	</parameter>

	<parameter>
		<parameterName>P_MAX_SINIESTROS</parameterName>
		<typeParameter>NUMERIC</typeParameter>
	</parameter>

	<parameter>
		<parameterName>P_USER</parameterName>
		<typeParameter>VARCHAR</typeParameter>
	</parameter>

	<parameter>
		<parameterName>P_PARTNERID</parameterName>
		<typeParameter>NUMERIC</typeParameter>
	</parameter>

	<parameter>
		<parameterName>P_ERROR</parameterName>
		<outParameter>true</outParameter>
		<typeParameter>NUMERIC</typeParameter>
	</parameter>

	<parameter>
		<parameterName>P_ERROR_DESC</parameterName>
		<outParameter>true</outParameter>
		<typeParameter>VARCHAR</typeParameter>
	</parameter>
</callSP>

=== JonathanOReyesA/SIMA/common/persistence/src/main/resources/xml/callSP-SPALTASEGUROSPE.xml
<?xml version="1.0" encoding="UTF-8"?>
<callSP xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="callSP.xsd">
  <storedProcedureName>SPALTASEGUROS_PE</storedProcedureName>

  <parameter>
  	<parameterName>P_REG_LEI</parameterName>
  	<outParameter>true</outParameter>
  	<typeParameter>NUMERIC</typeParameter>
  </parameter>
  
   <parameter>
  	<parameterName>P_REG_PROC</parameterName>
  	<outParameter>true</outParameter>
  	<typeParameter>NUMERIC</typeParameter>
  </parameter>
  
  
   <parameter>
  	<parameterName>P_REG_RECHAZA</parameterName>
  	<outParameter>true</outParameter>
  	<typeParameter>NUMERIC</typeParameter>
  </parameter>

  
   <parameter>
  	<parameterName>P_ERROR</parameterName>
  	<outParameter>true</outParameter>
  	<typeParameter>NUMERIC</typeParameter>
  </parameter>
  
   <parameter>
  	<parameterName>P_ERRORDESC</parameterName>
  	<outParameter>true</outParameter>
  	<typeParameter>VARCHAR</typeParameter>
  </parameter>
</callSP>
