=== JonathanOReyesA/SIMA/common/persistence/src/main/resources/xml/callSP.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns="http://www.w3.org/2001/XMLSchema">
  <element name="callSP">
    <complexType>
      <sequence>
        <element type="string" name="storedProcedureName"/>
        <element type="boolean" name="function" minOccurs="0"/>
        <element type="boolean" name="cursor" minOccurs="0"/>
        <element name="parameter" maxOccurs="unbounded" minOccurs="0">
          <complexType>
            <sequence>
              <element type="string" name="parameterName"/>
              <element type="string" name="outParameter" minOccurs="0"/>
              <element type="string" name="typeParameter"/>
            </sequence>
          </complexType>
        </element>
        <element name="result" maxOccurs="unbounded" minOccurs="0">
          <complexType>
            <sequence>
              <element type="string" name="errorCodeParameterName"/>
              <element type="string" name="errorDescriptionParameterName" minOccurs="0"/>
              <element type="integer" name="successExecuteSPCode"/>
              <element type="string" name="successExecuteSPDescription" minOccurs="0"/>
              <element type="integer" name="errorExecuteSPCode" minOccurs="0"/>
              <element type="string" name="errorExecuteSPDescription" minOccurs="0"/>
            </sequence>
          </complexType>
        </element>
      </sequence>
    </complexType>
  </element>
</schema>

=== JonathanOReyesA/SIMA/common/persistence/src/main/resources/xml/callSP-SPGETINSURANCEROBO_V2.xml
<?xml version="1.0" encoding="UTF-8"?>
<callSP xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="callSP.xsd">
  <storedProcedureName>SPGETINSURANCEROBO_V2</storedProcedureName>
  <function>true</function>
  <cursor>true</cursor>
  <parameter>
  	<parameterName>P_RECORDS</parameterName>
  	<outParameter>true</outParameter>
  	<typeParameter>NUMERIC</typeParameter>
  </parameter>
</callSP>

=== JonathanOReyesA/SIMA/common/persistence/src/main/resources/xml/callSP-SPALTASEGUROS_ROBO.xml
<?xml version="1.0" encoding="UTF-8"?>
<callSP xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="callSP.xsd">
  <storedProcedureName>SPALTASEGUROS_ROBO</storedProcedureName>
  
  
  <parameter>
  	<parameterName>P_REG_LEI</parameterName>
  	<outParameter>true</outParameter>
  	<typeParameter>NUMERIC</typeParameter>
  </parameter>
  
   <parameter>
  	<parameterName>P_REG_PROC</parameterName>
  	<outParameter>true</outParameter>
  	<typeParameter>NUMERIC</typeParameter>
  </parameter>
  
  
   <parameter>
  	<parameterName>P_REG_REJECT</parameterName>
  	<outParameter>true</outParameter>
  	<typeParameter>NUMERIC</typeParameter>
  </parameter>
  
  <parameter>
  	<parameterName>P_FILE_ID</parameterName>
  	<outParameter>true</outParameter>
  	<typeParameter>NUMERIC</typeParameter>
  </parameter>
  
   <parameter>
  	<parameterName>P_ERROR</parameterName>
  	<outParameter>true</outParameter>
  	<typeParameter>VARCHAR</typeParameter>
  </parameter>
  
   <parameter>
  	<parameterName>P_ERRORDESC</parameterName>
  	<outParameter>true</outParameter>
  	<typeParameter>VARCHAR</typeParameter>
  </parameter>
</callSP>

=== JonathanOReyesA/SIMA/common/persistence/src/main/resources/xml/callSP-SPUPDATECLAIMDOCUMMENTSH.xml
<?xml version="1.0" encoding="UTF-8"?>
<callSP xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="callSP.xsd">
  <storedProcedureName>SPUPDATECLAIMDOCUMMENTSH</storedProcedureName>
  	<parameter>
  		<parameterName>P_UUID</parameterName>
  		<typeParameter>VARCHAR</typeParameter>
  	</parameter>
    <parameter>
  		<parameterName>P_CREATIONDATETIME</parameterName>
  		<typeParameter>DATE</typeParameter>
  	</parameter>
    <parameter>
  		<parameterName>P_PARTNERID</parameterName>
  		<typeParameter>NUMERIC</typeParameter>
  	</parameter>
    <parameter>
  		<parameterName>P_TOTALRECORDS</parameterName>
  		<typeParameter>NUMERIC</typeParameter>
  	</parameter>
    <parameter>
  		<parameterName>P_ERROR</parameterName>
  		<outParameter>true</outParameter>
  		<typeParameter>NUMERIC</typeParameter>
  	</parameter>
    <parameter>
  		<parameterName>P_ERROR_DESC</parameterName>
  		<outParameter>true</outParameter>
  		<typeParameter>VARCHAR</typeParameter>
  	</parameter>
  
  	<result>
  		<errorCodeParameterName>P_ERROR</errorCodeParameterName>
  		<errorDescriptionParameterName>P_ERROR_DESC</errorDescriptionParameterName>
  		<successExecuteSPCode>0</successExecuteSPCode>
  	</result>
</callSP>

=== JonathanOReyesA/SIMA/common/persistence/src/main/resources/xml/callSP-SPGETINSURANCE.xml
<?xml version="1.0" encoding="UTF-8"?>
<callSP xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="callSP.xsd">
  <storedProcedureName>SPGETINSURANCE</storedProcedureName>
  <function>true</function>
  <cursor>true</cursor>
  
  <parameter>
  	<parameterName>P_INSURANCEID</parameterName>
  	<typeParameter>VARCHAR</typeParameter>
  </parameter>
  
   <parameter>
  	<parameterName>P_PRODUCTID</parameterName>
  	<typeParameter>VARCHAR</typeParameter>
  </parameter>
  
   <parameter>
  	<parameterName>P_GIVENNAME</parameterName>
  	<typeParameter>VARCHAR</typeParameter>
  </parameter>
  
  <parameter>
  	<parameterName>P_FAMILYNAME</parameterName>
  	<typeParameter>VARCHAR</typeParameter>
  </parameter>
  
   <parameter>
  	<parameterName>P_MIDDLENAME</parameterName>
  	<typeParameter>VARCHAR</typeParameter>
  </parameter>
  
   <parameter>
  	<parameterName>P_ADDITIONALFAMILYNAME</parameterName>
  	<typeParameter>VARCHAR</typeParameter>
  </parameter>
  
    <parameter>
  	<parameterName>P_BIRTHDATE</parameterName>
  	<typeParameter>DATE</typeParameter>
  </parameter>
  
   <parameter>
  	<parameterName>P_CERTIFICATE</parameterName>
  	<typeParameter>VARCHAR</typeParameter>
  </parameter>
  
  <parameter>
  	<parameterName>P_BUSINESSPARTNERID</parameterName>
  	<typeParameter>VARCHAR</typeParameter>
  </parameter>
  
  <parameter>
  	<parameterName>P_PARTNERID</parameterName>
  	<typeParameter>NUMERIC</typeParameter>
  </parameter>
  
 
</callSP>

=== JonathanOReyesA/SIMA/common/persistence/src/main/resources/xml/callSP-SPCIFCTL_PE.xml
<?xml version="1.0" encoding="UTF-8"?>
<callSP xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="callSP.xsd">
  <storedProcedureName>SPCIFCTL_PE</storedProcedureName>

  <parameter>
  	<parameterName>P_FILENAME</parameterName>
  	<typeParameter>VARCHAR</typeParameter>
  </parameter>
  
   <parameter>
  	<parameterName>P_REG_LEI</parameterName>
  	<typeParameter>NUMERIC</typeParameter>
  </parameter>
  
  
   <parameter>
  	<parameterName>P_REG_PROC</parameterName>
  	<typeParameter>NUMERIC</typeParameter>
  </parameter>
  
  <parameter>
  	<parameterName>P_REG_RECHAZA</parameterName>
  	<typeParameter>NUMERIC</typeParameter>
  </parameter>
  
   <parameter>
  	<parameterName>P_STARTDATE</parameterName>
  	<typeParameter>TIMESTAMP</typeParameter>
  </parameter>
  
   <parameter>
  	<parameterName>P_ENDDATE</parameterName>
  	<typeParameter>TIMESTAMP</typeParameter>
  </parameter>
</callSP>

=== JonathanOReyesA/SIMA/common/persistence/target/classes/xml/callSP-SPUPDATECLAIM.xml
<?xml version="1.0" encoding="UTF-8"?>
<callSP xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="callSP.xsd">
	<storedProcedureName>SPUPDATECLAIM</storedProcedureName>
	<parameter>
		<parameterName>P_CLAIMID</parameterName>
		<typeParameter>VARCHAR</typeParameter>
	</parameter>
	<parameter>
		<parameterName>P_CLAIMDATE</parameterName>
		<typeParameter>DATE</typeParameter>
	</parameter>
	<parameter>
		<parameterName>P_DOCUMENTNAME</parameterName>
		<typeParameter>VARCHAR</typeParameter>
	</parameter>
	<parameter>
		<parameterName>P_DOCUMENTDATE</parameterName>
		<typeParameter>DATE</typeParameter>
	</parameter>
	
	<parameter>
		<parameterName>P_GIVENNAME</parameterName>
		<typeParameter>VARCHAR</typeParameter>
	</parameter>

	<parameter>
		<parameterName>P_MIDDLENAME</parameterName>
		<typeParameter>VARCHAR</typeParameter>
	</parameter>

	<parameter>
		<parameterName>P_FAMILYNAME</parameterName>
		<typeParameter>VARCHAR</typeParameter>
	</parameter>

	<parameter>
		<parameterName>P_ADDITIONALFAMILYNAME</parameterName>
		<typeParameter>VARCHAR</typeParameter>
	</parameter>

	<parameter>
		<parameterName>P_TRACKINGEMAIL</parameterName>
		<typeParameter>VARCHAR</typeParameter>
	</parameter>

	<parameter>
		<parameterName>P_CLAIMCAUSEID</parameterName>
		<typeParameter>NUMERIC</typeParameter>
	</parameter>


	<parameter>
		<parameterName>P_IDPERSONPAYABLE</parameterName>
		<typeParameter>VARCHAR</typeParameter>
	</parameter>


	<parameter>
		<parameterName>P_ERROR</parameterName>
		<outParameter>true</outParameter>
		<typeParameter>NUMERIC</typeParameter>
	</parameter>

	<parameter>
		<parameterName>P_ERROR_DESC</parameterName>
		<outParameter>true</outParameter>
		<typeParameter>VARCHAR</typeParameter>
	</parameter>


</callSP>

=== JonathanOReyesA/SIMA/common/persistence/src/main/resources/xml/callSP-GETAMOUNTTOPAY.xml
<?xml version="1.0" encoding="UTF-8"?>
<callSP xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="callSP.xsd">
  <storedProcedureName>GETAMOUNTTOPAY</storedProcedureName>
  <function>true</function>
  <cursor>true</cursor>
  <parameter>
  	<parameterName>P_INSURANCEID</parameterName>
  	<typeParameter>VARCHAR</typeParameter>
  </parameter>
   <parameter>
  	<parameterName>P_BUSINESSPARTNERID</parameterName>
  	<typeParameter>VARCHAR</typeParameter>
  </parameter>
   <parameter>
  	<parameterName>P_PRODUCTID</parameterName>
  	<typeParameter>VARCHAR</typeParameter>
  </parameter>
   <parameter>
  	<parameterName>P_COVERAGEID</parameterName>
  	<typeParameter>NUMERIC</typeParameter>
  </parameter>
  
  <parameter>
  	<parameterName>P_FLAGCOVERAGE</parameterName>
  	<typeParameter>NUMERIC</typeParameter>
  </parameter>
  
  <parameter>
  	<parameterName>P_CLAIMDAYS</parameterName>
  	<typeParameter>NUMERIC</typeParameter>
  </parameter>
  
  <parameter>
  	<parameterName>P_INITIAL_DATE</parameterName>
  	<typeParameter>DATE</typeParameter>
  </parameter>
  
    <parameter>
  	<parameterName>P_END_DATE</parameterName>
  	<typeParameter>DATE</typeParameter>
  </parameter>
  
    <parameter>
  	<parameterName>P_PARTNERID</parameterName>
  	<typeParameter>NUMERIC</typeParameter>
  </parameter>
  
   <parameter>
  	<parameterName>P_REMAINING</parameterName>
  		<outParameter>true</outParameter>
  	<typeParameter>NUMERIC</typeParameter>
  </parameter>
  
   <parameter>
  	<parameterName>P_CALCDAYS</parameterName>
  		<outParameter>true</outParameter>
  	<typeParameter>NUMERIC</typeParameter>
  </parameter>
  
   <parameter>
  	<parameterName>P_ERROR</parameterName>
  		<outParameter>true</outParameter>
  	<typeParameter>NUMERIC</typeParameter>
  </parameter>
    <parameter>
  	<parameterName>P_ERROR_DESC</parameterName>
  		<outParameter>true</outParameter>
  	<typeParameter>VARCHAR</typeParameter>
  </parameter>
  
</callSP>

=== JonathanOReyesA/SIMA/common/persistence/target/classes/xml/callSP-SPBENEFICIARYDATAUPDATE.xml
<?xml version="1.0" encoding="UTF-8"?>
<callSP xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="callSP.xsd">
	<storedProcedureName>SPBENEFICIARYDATAUPDATE</storedProcedureName>
	<parameter>
		<parameterName>P_INSURANCEID</parameterName>
		<typeParameter>VARCHAR</typeParameter>
	</parameter>
	<parameter>
		<parameterName>P_BENEFICIARYID</parameterName>
		<typeParameter>VARCHAR</typeParameter>
	</parameter>

	<parameter>
		<parameterName>P_PERCENTAGE</parameterName>
		<typeParameter>NUMERIC</typeParameter>
	</parameter>
	<parameter>
		<parameterName>P_RELATIONSHIP</parameterName>
		<typeParameter>VARCHAR</typeParameter>
	</parameter>

	<parameter>
		<parameterName>P_GIVENNAME</parameterName>
		<typeParameter>VARCHAR</typeParameter>
	</parameter>
	<parameter>
		<parameterName>P_MIDDLENAME</parameterName>
		<typeParameter>VARCHAR</typeParameter>
	</parameter>

	<parameter>
		<parameterName>P_FAMILYNAME</parameterName>
		<typeParameter>VARCHAR</typeParameter>
	</parameter>
	<parameter>
		<parameterName>P_ADDITIONALFAMILYNAME</parameterName>
		<typeParameter>VARCHAR</typeParameter>
	</parameter>


	<parameter>
		<parameterName>P_BIRTHDATE</parameterName>
		<typeParameter>DATE</typeParameter>
	</parameter>
	<parameter>
		<parameterName>P_GENDER</parameterName>
		<typeParameter>VARCHAR</typeParameter>
	</parameter>

	<parameter>
		<parameterName>P_HOMEPHONE</parameterName>
		<typeParameter>VARCHAR</typeParameter>
	</parameter>

	<parameter>
		<parameterName>P_OFFICEPHONE</parameterName>
		<typeParameter>VARCHAR</typeParameter>
	</parameter>

	<parameter>
		<parameterName>P_CELLPHONE</parameterName>
		<typeParameter>VARCHAR</typeParameter>
	</parameter>

	<parameter>
		<parameterName>P_MARRIEDFAMILYNAME</parameterName>
		<typeParameter>VARCHAR</typeParameter>
	</parameter>

	<parameter>
		<parameterName>P_PARTNERID</parameterName>
		<typeParameter>NUMERIC</typeParameter>
	</parameter>


	<parameter>
		<parameterName>P_ERROR</parameterName>
		<outParameter>true</outParameter>
		<typeParameter>NUMERIC</typeParameter>
	</parameter>
	<parameter>
		<parameterName>P_ERROR_DESC</parameterName>
		<outParameter>true</outParameter>
		<typeParameter>VARCHAR</typeParameter>
	</parameter>

</callSP>
