=== JonathanOReyesA/SIMA/common/persistence/src/main/resources/xml/callSP.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns="http://www.w3.org/2001/XMLSchema">
  <element name="callSP">
    <complexType>
      <sequence>
        <element type="string" name="storedProcedureName"/>
        <element type="boolean" name="function" minOccurs="0"/>
        <element type="boolean" name="cursor" minOccurs="0"/>
        <element name="parameter" maxOccurs="unbounded" minOccurs="0">
          <complexType>
            <sequence>
              <element type="string" name="parameterName"/>
              <element type="string" name="outParameter" minOccurs="0"/>
              <element type="string" name="typeParameter"/>
            </sequence>
          </complexType>
        </element>
        <element name="result" maxOccurs="unbounded" minOccurs="0">
          <complexType>
            <sequence>
              <element type="string" name="errorCodeParameterName"/>
              <element type="string" name="errorDescriptionParameterName" minOccurs="0"/>
              <element type="integer" name="successExecuteSPCode"/>
              <element type="string" name="successExecuteSPDescription" minOccurs="0"/>
              <element type="integer" name="errorExecuteSPCode" minOccurs="0"/>
              <element type="string" name="errorExecuteSPDescription" minOccurs="0"/>
            </sequence>
          </complexType>
        </element>
      </sequence>
    </complexType>
  </element>
</schema>

=== JonathanOReyesA/SIMA/common/persistence/target/classes/xml/callSP-SPCREATECLAIM.xml
<?xml version="1.0" encoding="UTF-8"?>
<callSP xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="callSP.xsd">
  <storedProcedureName>SPCREATECLAIM</storedProcedureName>

  <parameter>
  	<parameterName>P_INSURANCEID</parameterName>
  	<typeParameter>VARCHAR</typeParameter>
  </parameter>
   <parameter>
  	<parameterName>P_COVERAGEID</parameterName>
  	<typeParameter>NUMERIC</typeParameter>
  </parameter>
   <parameter>
  	<parameterName>P_CLAIMDATE</parameterName>
  	<typeParameter>DATE</typeParameter>
  </parameter>
   <parameter>
  	<parameterName>P_AFFECTED</parameterName>
  	<typeParameter>VARCHAR</typeParameter>
  </parameter>
  
   <parameter>
  	<parameterName>P_CLAIMCAUSEID</parameterName>
  	<typeParameter>NUMERIC</typeParameter>
  </parameter>
  
   <parameter>
  	<parameterName>P_STATUSID</parameterName>
  	<typeParameter>NUMERIC</typeParameter>
  </parameter>
  
   <parameter>
  	<parameterName>P_STATUSDATE</parameterName>
  	<typeParameter>TIMESTAMP</typeParameter>
  </parameter>
  
   <parameter>
  	<parameterName>P_USER</parameterName>
  	<typeParameter>VARCHAR</typeParameter>
  </parameter>
  
  
   <parameter>
  	<parameterName>P_TRACKINGEMAIL</parameterName>
  	<typeParameter>VARCHAR</typeParameter>
  </parameter>
  
  
   <parameter>
  	<parameterName>ProcessInstanceID</parameterName>
  	<typeParameter>VARCHAR</typeParameter>
  </parameter>
  
   <parameter>
  	<parameterName>P_BUSINESSPARTNERID</parameterName>
  	<typeParameter>VARCHAR</typeParameter>
  </parameter>
  
   <parameter>
  	<parameterName>P_CLAIMDAYS</parameterName>
  	<typeParameter>NUMERIC</typeParameter>
  </parameter>
  
  <parameter>
  	<parameterName>P_FLAGCOVERAGE</parameterName>
  	<typeParameter>NUMERIC</typeParameter>
  </parameter>
  
  <parameter>
  	<parameterName>P_INITIAL_DATE</parameterName>
  	<typeParameter>TIMESTAMP</typeParameter>
  </parameter>
  
  <parameter>
  	<parameterName>P_END_DATE</parameterName>
  	<typeParameter>TIMESTAMP</typeParameter>
  </parameter>
  
  <parameter>
  	<parameterName>P_CLAIMPAYMENTTYPE</parameterName>
  	<typeParameter>VARCHAR</typeParameter>
  </parameter>
  
  <parameter>
  	<parameterName>P_ID_MEDICO</parameterName>
  	<typeParameter>NUMERIC</typeParameter>
  </parameter>
  
  <parameter>
  	<parameterName>P_PARTNERID</parameterName>
  	<typeParameter>NUMERIC</typeParameter>
  </parameter>
  
    <parameter>
  	<parameterName>P_ERROR</parameterName>
  		<outParameter>true</outParameter>
  	<typeParameter>NUMERIC</typeParameter>
  </parameter>
  
  <parameter>
  	<parameterName>P_ERROR_DESC</parameterName>
  		<outParameter>true</outParameter>
  	<typeParameter>VARCHAR</typeParameter>
  </parameter>
  
  <parameter>
  	<parameterName>P_IDCLAIM</parameterName>
  		<outParameter>true</outParameter>
  	<typeParameter>VARCHAR</typeParameter>
  </parameter>
  
</callSP>

=== JonathanOReyesA/SIMA/common/persistence/target/classes/xml/callSP-SPTINVOICEREPORT.xml
<?xml version="1.0" encoding="UTF-8"?>
<callSP xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="callSP.xsd">
	<storedProcedureName>SPTINVOICEREPORT</storedProcedureName>
	<cursor>true</cursor>


	<parameter>
		<parameterName>P_SOCIO</parameterName>
		<typeParameter>NUMERIC</typeParameter>
	</parameter>

	<parameter>
		<parameterName>P_PRODUCTO</parameterName>
		<typeParameter>VARCHAR</typeParameter>
	</parameter>

	<parameter>
		<parameterName>P_REGISTER</parameterName>
		<typeParameter>VARCHAR</typeParameter>
	</parameter>


	<parameter>
		<parameterName>P_MODEID</parameterName>
		<typeParameter>VARCHAR</typeParameter>
	</parameter>

	<parameter>
		<parameterName>P_STARTDATE</parameterName>
		<typeParameter>DATE</typeParameter>
	</parameter>


	<parameter>
		<parameterName>P_ENDDATE</parameterName>
		<typeParameter>DATE</typeParameter>
	</parameter>




	<parameter>
		<parameterName>P_TOT_REG</parameterName>
		<outParameter>true</outParameter>
		<typeParameter>NUMERIC</typeParameter>
	</parameter>


	<parameter>
		<parameterName>P_TYPE</parameterName>
		<outParameter>true</outParameter>
		<typeParameter>NUMERIC</typeParameter>
	</parameter>

	<parameter>
		<parameterName>P_TYPE_DESCRIPTION</parameterName>
		<outParameter>true</outParameter>
		<typeParameter>VARCHAR</typeParameter>
	</parameter>

	<parameter>
		<parameterName>P_TOT_REGN</parameterName>
		<outParameter>true</outParameter>
		<typeParameter>NUMERIC</typeParameter>
	</parameter>

	<parameter>
		<parameterName>P_TYPEN</parameterName>
		<outParameter>true</outParameter>
		<typeParameter>NUMERIC</typeParameter>
	</parameter>

	<parameter>
		<parameterName>P_TYPE_DESCRIPTIONN</parameterName>
		<outParameter>true</outParameter>
		<typeParameter>VARCHAR</typeParameter>
	</parameter>

</callSP>

=== JonathanOReyesA/SIMA/common/persistence/src/main/resources/xml/callSP-SPCLAIMCOMMENTS.xml
<?xml version="1.0" encoding="UTF-8"?>
<callSP xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="callSP.xsd">
  <storedProcedureName>SPCLAIMCOMMENTS</storedProcedureName>

  <parameter>
  	<parameterName>P_CLAIMID</parameterName>
  	<typeParameter>VARCHAR</typeParameter>
  </parameter>
  
  <parameter>
  	<parameterName>P_COMMENT</parameterName>
  	<typeParameter>VARCHAR</typeParameter>
  </parameter>
  
  <parameter>
  	<parameterName>P_USERID</parameterName>
  	<typeParameter>VARCHAR</typeParameter>
  </parameter>
  
  <parameter>
  	<parameterName>P_DATE</parameterName>
  	<typeParameter>DATE</typeParameter>
  </parameter>
  
   <parameter>
  	<parameterName>P_STATUS</parameterName>
  	<typeParameter>VARCHAR</typeParameter>
  </parameter>

   <parameter>
  	<parameterName>P_ERROR</parameterName>
  	<outParameter>true</outParameter>
  	<typeParameter>NUMERIC</typeParameter>
  </parameter>
  
   <parameter>
  	<parameterName>P_ERRORDESC</parameterName>
  	<outParameter>true</outParameter>
  	<typeParameter>VARCHAR</typeParameter>
  </parameter>
</callSP>

=== JonathanOReyesA/SIMA/common/persistence/src/main/resources/xml/callSP-FNGETINDICADORES.xml
<?xml version="1.0" encoding="UTF-8"?>
<callSP xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="callSP.xsd">
	<storedProcedureName>FNGETINDICADORES</storedProcedureName>

	<function>true</function>
	<cursor>true</cursor>

	<parameter>
		<parameterName>P_CERTIFICATE</parameterName>
		<typeParameter>VARCHAR</typeParameter>
	</parameter>
	<parameter>
		<parameterName>P_COVERAGEID</parameterName>
		<typeParameter>NUMERIC</typeParameter>
	</parameter>

	<parameter>
		<parameterName>P_PARTNERID</parameterName>
		<typeParameter>NUMERIC</typeParameter>
	</parameter>
</callSP>

=== JonathanOReyesA/SIMA/common/persistence/src/main/resources/xml/callSP-SPGETCOVERAGE_PE.xml
<?xml version="1.0" encoding="UTF-8"?>
<callSP xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="callSP.xsd">
  <storedProcedureName>SPGETCOVERAGE_PE</storedProcedureName>
  <function>true</function>
  <cursor>true</cursor>
  <parameter>
  	<parameterName>P_PRODUCTID</parameterName>
  	<typeParameter>VARCHAR</typeParameter>
  </parameter>
  
    <parameter>
  	<parameterName>P_MODEID</parameterName>
  	<typeParameter>VARCHAR</typeParameter>
  </parameter>
  
    <parameter>
  	<parameterName>P_FLAG</parameterName>
  	<typeParameter>VARCHAR</typeParameter>
  </parameter>
  
  <parameter>
  	<parameterName>P_PARTNERID</parameterName>
  	<typeParameter>NUMERIC</typeParameter>
  </parameter>
  
</callSP>

=== JonathanOReyesA/SIMA/common/persistence/src/main/resources/xml/callSP-SPSEARCHCOVERAGEDOCUMENTS.xml
<?xml version="1.0" encoding="UTF-8"?>
<callSP xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="callSP.xsd">
  <storedProcedureName>SPSEARCHCOVERAGEDOCUMENTS</storedProcedureName>
  <function>true</function>
  <cursor>true</cursor>
  
  
  <parameter>
  	<parameterName>P_COVERAGECATALOGUEID</parameterName>
  	<typeParameter>VARCHAR</typeParameter>
  </parameter>
  <parameter>
  	<parameterName>P_RELATIONSHIPCODE</parameterName>
  	<typeParameter>VARCHAR</typeParameter>
  </parameter>

</callSP>

=== JonathanOReyesA/SIMA/common/persistence/target/classes/xml/callSP-FNGETPROMOTOR_OS.xml
<?xml version="1.0" encoding="UTF-8"?>
<callSP xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="callSP.xsd">
	<storedProcedureName>FNGETPROMOTOR_OS</storedProcedureName>
	<function>true</function>
	<cursor>true</cursor>

	<parameter>
		<parameterName>P_CERTIFICATE</parameterName>
		<typeParameter>VARCHAR</typeParameter>
	</parameter>
	<parameter>
		<parameterName>P_PARTNERID</parameterName>
		<typeParameter>NUMERIC</typeParameter>
	</parameter>
</callSP>

=== JonathanOReyesA/SIMA/common/persistence/target/classes/xml/callSP-SPCREATEUPDATEHOSPITAL.xml
<?xml version="1.0" encoding="UTF-8"?>
<callSP xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="callSP.xsd">
	<storedProcedureName>SPCREATEUPDATEHOPITAL</storedProcedureName>

	<parameter>
		<parameterName>P_ID_HOSPITAL</parameterName>
		<typeParameter>NUMERIC</typeParameter>
	</parameter>

	<parameter>
		<parameterName>P_NOMBRE</parameterName>
		<typeParameter>VARCHAR</typeParameter>
	</parameter>

	<parameter>
		<parameterName>P_RFC</parameterName>
		<typeParameter>VARCHAR</typeParameter>
	</parameter>

	<parameter>
		<parameterName>P_DESCRIPCION</parameterName>
		<typeParameter>VARCHAR</typeParameter>
	</parameter>

	<parameter>
		<parameterName>P_ID_TYPE</parameterName>
		<typeParameter>NUMERIC</typeParameter>
	</parameter>

	<parameter>
		<parameterName>P_CALLE_NUMERO</parameterName>
		<typeParameter>VARCHAR</typeParameter>
	</parameter>

	<parameter>
		<parameterName>P_COLONIA</parameterName>
		<typeParameter>VARCHAR</typeParameter>
	</parameter>

	<parameter>
		<parameterName>P_CIUDAD</parameterName>
		<typeParameter>VARCHAR</typeParameter>
	</parameter>

	<parameter>
		<parameterName>P_ESTADO</parameterName>
		<typeParameter>VARCHAR</typeParameter>
	</parameter>

	<parameter>
		<parameterName>P_CP</parameterName>
		<typeParameter>VARCHAR</typeParameter>
	</parameter>

	<parameter>
		<parameterName>P_STATUS</parameterName>
		<typeParameter>VARCHAR</typeParameter>
	</parameter>

	<parameter>
		<parameterName>P_USER</parameterName>
		<typeParameter>VARCHAR</typeParameter>
	</parameter>

	<parameter>
		<parameterName>P_PARTNERID</parameterName>
		<typeParameter>NUMERIC</typeParameter>
	</parameter>

	<parameter>
		<parameterName>P_ERROR</parameterName>
		<outParameter>true</outParameter>
		<typeParameter>NUMERIC</typeParameter>
	</parameter>

	<parameter>
		<parameterName>P_ERROR_DESC</parameterName>
		<outParameter>true</outParameter>
		<typeParameter>VARCHAR</typeParameter>
	</parameter>
</callSP>
